dist: xenial
language: go
sudo: true

go:
  - "tip"
  - "1.12.x"
  - "1.11.x"
  - "1.10.x"
  - "1.9.x"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y clang llvm clang-format

script:
  # Verify for .go formatting issues
  - if [ -n "$(gofmt -l .)" ]; then echo "Please fix source formatting by 'go fmt ./...'"; false; fi
  # Verify for  .c/.h formatting issues
  - |
    export CLANG_FORMAT_CMD=( git-clang-format --style="{BasedOnStyle: Google, IndentWidth: 2}" --extensions=c,cpp,h );
    ${CLANG_FORMAT_CMD[@]} --diff | egrep "^no modified files to format$" &> /dev/null
  - |
    if [ $? -ne 0 ]; then
      "${CLANG_FORMAT_CMD[@]}" --diff;
      echo -e "\n\nclang-format failed. Please apt-get install clang-format and format source by:\n";
      printf '%q ' "${CLANG_FORMAT_CMD[@]}";
      echo -e "HEAD~\n";
      exit 1;
    fi
  # Run unit tests
  - go test -v -coverprofile=coverage.txt -covermode=atomic
  - cd goebpf_mock && go test -v -coverprofile=coverage.txt -covermode=atomic
  # Travis does not support operations with eBPF, so, just ensure that
  # integration test is compilable Run integration test
  - cd ../itest && make

after_success:
  - bash <(curl -s https://codecov.io/bash)
